Quick fix for missing field
A newly forked repository by olatarkowska
led to the following error:

```
  File ".../site-packages/scc/git.py", line 1935, in get_merge_remotes
    if repo.private:
AttributeError: 'NoneType' object has no attribute 'private'
```